name: Pull Request Checks
on: [ pull_request ]

jobs:

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print commitlint.config.js
        run: cat .configs/commitlint.config.js

      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .configs/commitlint.config.js